'use client';

import { useEffect, useMemo, useRef, useState } from 'react';

type Inputs = { projectName:string; location:string; owner:string; roofArea:number; pvCapacity:number; storagePower:number; storageCapacity:number; investment:number; electricityPrice:number; annualUse:number; selfUseRate:number; loanRatio:number; loanRate:number; loanYears:number };
const initial:Inputs={projectName:'华东智造产业园零碳改造项目',location:'浙江省温州市',owner:'示范园区有限公司',roofArea:82000,pvCapacity:8000,storagePower:2000,storageCapacity:4000,investment:4680,electricityPrice:.82,annualUse:2280,selfUseRate:88,loanRatio:70,loanRate:3.2,loanYears:10};
const nav=[['01','项目信息'],['02','测算结果'],['03','风险诊断'],['04','报告预览']];
function Field({label,value,unit,onChange,step=1}:{label:string;value:number;unit:string;onChange:(v:number)=>void;step?:number}){return <label className="field"><span>{label}</span><div><input type="number" min="0" step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/><b>{unit}</b></div></label>}
function Money({value}:{value:number}){return <>{value.toLocaleString('zh-CN',{maximumFractionDigits:1})}</>}
function LineChart({values}:{values:number[]}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current;if(!c)return;const dpr=devicePixelRatio||1,box=c.getBoundingClientRect();c.width=box.width*dpr;c.height=box.height*dpr;const x=c.getContext('2d');if(!x)return;x.scale(dpr,dpr);const w=box.width,h=box.height,p=28,max=Math.max(...values)*1.08,min=Math.min(0,...values);x.strokeStyle='#dce8e2';x.lineWidth=1;for(let i=0;i<5;i++){const y=p+(h-p*2)*i/4;x.beginPath();x.moveTo(p,y);x.lineTo(w-p,y);x.stroke()}x.strokeStyle='#148257';x.lineWidth=3;x.lineJoin='round';x.beginPath();values.forEach((v,i)=>{const px=p+(w-p*2)*i/(values.length-1),py=h-p-(v-min)/(max-min)*(h-p*2);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();values.forEach((v,i)=>{const px=p+(w-p*2)*i/(values.length-1),py=h-p-(v-min)/(max-min)*(h-p*2);x.fillStyle='#fff';x.strokeStyle='#148257';x.lineWidth=2;x.beginPath();x.arc(px,py,4,0,Math.PI*2);x.fill();x.stroke()})},[values]);return <canvas ref={ref} className="line-chart" aria-label="20年累计现金流折线图"/>}

export default function Home(){
 const[page,setPage]=useState(0),[data,setData]=useState(initial),[saved,setSaved]=useState(false);const set=<K extends keyof Inputs>(k:K,v:Inputs[K])=>{setData(d=>({...d,[k]:v}));setSaved(false)};
 const m=useMemo(()=>{const generation=data.pvCapacity*1100/10000,pvSaving=generation*10000*(data.selfUseRate/100)*data.electricityPrice/10000,exportIncome=generation*10000*(1-data.selfUseRate/100)*.36/10000,storageIncome=data.storageCapacity*300*.45/10000,annualIncome=pvSaving+exportIncome+storageIncome,annualOpex=data.investment*.012,net=annualIncome-annualOpex,payback=data.investment/Math.max(net,1),irr=Math.max(0,Math.min(30,net/data.investment*100-1.3)),carbon=generation*5.7,loan=data.investment*data.loanRatio/100,rate=data.loanRate/100,annualDebt=loan*(rate*Math.pow(1+rate,data.loanYears))/(Math.pow(1+rate,data.loanYears)-1),dscr=net/Math.max(annualDebt,1),cash=Array.from({length:21},(_,i)=>i===0?-data.investment:-data.investment+net*i);return{generation,pvSaving,storageIncome,annualIncome,annualOpex,net,payback,irr,carbon,loan,annualDebt,dscr,cash}},[data]);
 const risks=[['项目经济性',m.irr>=8?'绿':m.irr>=6?'黄':'红',`IRR ${m.irr.toFixed(1)}%`],['偿债能力',m.dscr>=1.3?'绿':m.dscr>=1.1?'黄':'红',`DSCR ${m.dscr.toFixed(2)}`],['负荷匹配',data.selfUseRate>=85?'绿':data.selfUseRate>=70?'黄':'红',`自用率 ${data.selfUseRate}%`],['技术可行性',data.roofArea/data.pvCapacity>=8?'绿':'黄','屋顶容量匹配'],['手续完备度','黄','待补并网意见'],['主体信用','绿','经营情况稳定'],['绿色合规','绿','符合绿色项目目录']];const green=risks.filter(r=>r[1]==='绿').length,yellow=risks.filter(r=>r[1]==='黄').length,score=Math.round((green*14+yellow*8)/.98);
 return <main><header className="topbar"><div className="brand"><span className="logo">零</span><div><strong>零碳智评</strong><small>园区新能源投融资决策平台</small></div></div><div className="top-actions"><span className={saved?'saved':'draft'}>{saved?'已保存':'草稿未保存'}</span><button className="ghost" onClick={()=>setData(initial)}>恢复示例</button><button className="primary" onClick={()=>setSaved(true)}>保存项目</button></div></header><div className="shell"><aside className="sidebar"><div className="project-mini"><span>当前项目</span><strong>{data.projectName}</strong><em>测算版本 V1.0</em></div><nav>{nav.map((n,i)=><button key={n[0]} className={page===i?'active':''} onClick={()=>setPage(i)}><b>{n[0]}</b><span>{n[1]}</span>{i<3&&<i className={page>i?'done':''}/>}</button>)}</nav><div className="help"><b>模型口径</b><p>示例模型用于产品演示，正式融资需以尽调数据及金融机构口径复核。</p></div></aside><section className="content">
 {page===0&&<><div className="page-title"><div><span>STEP 01 / 04</span><h1>项目信息录入</h1><p>填写园区用能、设备方案和融资参数，系统将实时生成投资评估。</p></div><button className="primary big" onClick={()=>setPage(1)}>开始测算 →</button></div><div className="grid two"><article className="card"><h2><i>01</i>基本信息</h2><label className="text-field"><span>项目名称</span><input value={data.projectName} onChange={e=>set('projectName',e.target.value)}/></label><div className="form-grid"><label className="text-field"><span>项目地点</span><input value={data.location} onChange={e=>set('location',e.target.value)}/></label><label className="text-field"><span>项目业主</span><input value={data.owner} onChange={e=>set('owner',e.target.value)}/></label></div><div className="form-grid"><Field label="可用屋顶面积" value={data.roofArea} unit="㎡" onChange={v=>set('roofArea',v)}/><Field label="园区年用电量" value={data.annualUse} unit="万kWh" onChange={v=>set('annualUse',v)}/></div></article><article className="card"><h2><i>02</i>设备方案</h2><div className="form-grid"><Field label="光伏装机容量" value={data.pvCapacity} unit="kWp" onChange={v=>set('pvCapacity',v)}/><Field label="储能功率" value={data.storagePower} unit="kW" onChange={v=>set('storagePower',v)}/><Field label="储能容量" value={data.storageCapacity} unit="kWh" onChange={v=>set('storageCapacity',v)}/><Field label="光伏自用率" value={data.selfUseRate} unit="%" onChange={v=>set('selfUseRate',v)}/></div><div className="hint">系统建议：当前屋顶面积可支撑约 {(data.roofArea/8).toFixed(0)} kWp 光伏容量。</div></article><article className="card"><h2><i>03</i>投资与电价</h2><div className="form-grid"><Field label="项目总投资" value={data.investment} unit="万元" onChange={v=>set('investment',v)}/><Field label="综合用电价格" value={data.electricityPrice} unit="元/kWh" step={.01} onChange={v=>set('electricityPrice',v)}/></div></article><article className="card"><h2><i>04</i>融资假设</h2><div className="form-grid"><Field label="贷款比例" value={data.loanRatio} unit="%" onChange={v=>set('loanRatio',v)}/><Field label="贷款利率" value={data.loanRate} unit="%" step={.1} onChange={v=>set('loanRate',v)}/><Field label="贷款期限" value={data.loanYears} unit="年" onChange={v=>set('loanYears',v)}/></div></article></div></>}
 {page===1&&<><div className="page-title"><div><span>STEP 02 / 04</span><h1>碳测算与财务结果</h1><p>基于当前参数形成统一口径的项目收益与减排结果。</p></div><button className="outline" onClick={()=>setPage(0)}>← 调整参数</button></div><div className="metrics"><div><span>项目 IRR</span><strong>{m.irr.toFixed(1)}%</strong><em className="up">高于基准收益率</em></div><div><span>静态回收期</span><strong>{m.payback.toFixed(1)}年</strong><em>全投资口径</em></div><div><span>年净收益</span><strong><Money value={m.net}/>万</strong><em>扣除年度运维</em></div><div><span>年减排量</span><strong><Money value={m.carbon}/>吨</strong><em>CO₂e</em></div><div><span>偿债覆盖率</span><strong>{m.dscr.toFixed(2)}</strong><em className={m.dscr>=1.3?'up':'warn'}>{m.dscr>=1.3?'偿债安全':'需优化融资'}</em></div></div><div className="grid result-grid"><article className="card chart-card"><div className="card-head"><h2>20年累计现金流</h2><span>单位：万元</span></div><LineChart values={m.cash}/><div className="year-axis"><span>建设期</span><span>第5年</span><span>第10年</span><span>第15年</span><span>第20年</span></div></article><article className="card"><div className="card-head"><h2>年度收益构成</h2><span><Money value={m.annualIncome}/> 万元</span></div><div className="bars"><div style={{'--w':`${m.pvSaving/m.annualIncome*100}%`} as React.CSSProperties}><span>光伏自用节省</span><i/><b><Money value={m.pvSaving}/></b></div><div style={{'--w':`${(m.annualIncome-m.pvSaving-m.storageIncome)/m.annualIncome*100}%`} as React.CSSProperties}><span>余电上网</span><i/><b><Money value={m.annualIncome-m.pvSaving-m.storageIncome}/></b></div><div style={{'--w':`${m.storageIncome/m.annualIncome*100}%`} as React.CSSProperties}><span>储能套利</span><i/><b><Money value={m.storageIncome}/></b></div></div><hr/><div className="calc-list"><p><span>预计年发电量</span><b><Money value={m.generation}/> 万kWh</b></p><p><span>年度运维费用</span><b><Money value={m.annualOpex}/> 万元</b></p><p><span>贷款金额</span><b><Money value={m.loan}/> 万元</b></p><p><span>年度偿债额</span><b><Money value={m.annualDebt}/> 万元</b></p></div></article></div><article className="insight"><b>AI 测算解读</b><p>项目收益主要由光伏自发自用贡献。当前方案经济性较好；若要提高抗风险能力，建议优先锁定园区长期负荷与电价机制，并核实并网消纳条件。</p><button onClick={()=>setPage(2)}>查看风险诊断 →</button></article></>}
 {page===2&&<><div className="page-title"><div><span>STEP 03 / 04</span><h1>七维风险诊断</h1><p>从金融机构视角识别项目短板，明确融资前的补充动作。</p></div><button className="primary big" onClick={()=>setPage(3)}>生成一页报告 →</button></div><div className="risk-summary"><div className="score"><small>综合融资准备度</small><strong>{score}</strong><span>/ 100</span></div><div><h2>项目整体处于“基本可融资”阶段</h2><p>{green} 项表现良好，{yellow} 项需要补充，{7-green-yellow} 项存在明显风险。建议完成并网意见及关键合同后启动银行预沟通。</p><div className="legend"><i className="g"/>通过 <i className="y"/>关注 <i className="r"/>风险</div></div></div><div className="risk-list">{risks.map((r,i)=><article key={r[0]}><div className={`light ${r[1]}`}/><b>{String(i+1).padStart(2,'0')}</b><div><h3>{r[0]}</h3><p>{r[2]}</p></div><span className={`tag ${r[1]}`}>{r[1]==='绿'?'通过':r[1]==='黄'?'需关注':'高风险'}</span><em>{r[1]==='黄'?'补充材料 →':r[1]==='红'?'立即优化 →':'查看依据 →'}</em></article>)}</div><article className="action-box"><b>优先行动建议</b><ol><li>补充电网接入意见或并网批复，确认消纳边界。</li><li>取得近12个月分时负荷数据，校准光伏自用率与储能收益。</li><li>与合作银行预沟通贷款期限、还款方式及增信要求。</li></ol></article></>}
 {page===3&&<><div className="page-title"><div><span>STEP 04 / 04</span><h1>一页报告预览</h1><p>把核心结论整理为园区、正泰和金融机构都能快速阅读的标准摘要。</p></div><div className="button-row"><button className="outline" onClick={()=>window.print()}>打印 / 导出 PDF</button><button className="primary big" onClick={()=>alert('演示功能：正式版将生成授信材料包。')}>生成授信材料包</button></div></div><article className="report" id="report"><header><div><span className="report-logo">零碳智评</span><h2>{data.projectName}</h2><p>新能源项目投融资评估摘要｜测算版本 V1.0</p></div><div><b>基本可融资</b><small>评估日期：2026-08-28</small></div></header><section className="report-kpis"><div><small>总投资</small><strong><Money value={data.investment}/> 万元</strong></div><div><small>项目 IRR</small><strong>{m.irr.toFixed(1)}%</strong></div><div><small>回收期</small><strong>{m.payback.toFixed(1)} 年</strong></div><div><small>年减排</small><strong><Money value={m.carbon}/> 吨</strong></div><div><small>准备度</small><strong>{score} 分</strong></div></section><div className="report-body"><section><h3>项目概况</h3><p>{data.location}｜屋顶面积 {data.roofArea.toLocaleString()} ㎡｜光伏 {data.pvCapacity.toLocaleString()} kWp｜储能 {data.storagePower.toLocaleString()} kW / {data.storageCapacity.toLocaleString()} kWh。</p><h3>财务判断</h3><p>预计年净收益 <Money value={m.net}/> 万元，偿债覆盖率 {m.dscr.toFixed(2)}。在当前电价、自用率和融资假设下，项目具备继续推进价值。</p><h3>碳减排效益</h3><p>预计年发电量 <Money value={m.generation}/> 万kWh，对应年减排约 <Money value={m.carbon}/> 吨 CO₂e，可支撑绿色项目认定与环境效益披露。</p></section><section><h3>七维诊断</h3>{risks.map(r=><p className="report-risk" key={r[0]}><i className={r[1]}/><span>{r[0]}</span><b>{r[1]==='绿'?'通过':r[1]==='黄'?'关注':'风险'}</b></p>)}<h3>融资建议</h3><p>建议优先匹配中长期绿色项目贷款，贷款比例控制在 {data.loanRatio}% 左右，并在正式申报前补齐并网意见、负荷数据与核心合同。</p></section></div><footer>本报告由示例模型自动生成，仅用于产品演示，不构成投资或授信承诺。</footer></article></>}
 </section></div></main>
}

